server:
  port: 8080

spring: 
  application: 
    name: bootDemo
      
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 100
    maxIdle: 50
    minIdle: 10
    initialSize: 10
    maxWait: 100
    connectionTimeout: 500
    testWhileIdle: true
    validationQuery: SELECT 1 FROM DUAL
    validationQueryTimeout: 100
    
  redis:
    #password: 
    clusterNodes: 172.16.2.55:6000,172.16.2.55:7000,172.16.2.55:8000,172.16.2.56:6000,172.16.2.56:7000,172.16.2.56:8000
    #expireSeconds: 120
    commandTimeout: 10000  #redis操作的超时时间
    maxActive: 5000 #最大连接数
    maxIdle: 30 #最大空闲连接数
    minIdle: 5 #最小空闲连接数
    maxWait: 3000  #获取连接最大等待时间 ms  #default -1

   
mybatis:
  configuration.jdbcTypeForNull: 'NULL'
  mapperLocations: classpath:mapper/**/*Mapper.xml
 
#定义一些常量
com.github.nyc.url: www.baidu.com
com.github.nyc.name: nieyc
spring.application.name: bootDemo

#日志
logging:
  file: ./logs/spring-boot
  level:
   com.github.nyc.bootDemo: DEBUG
   org.springframework.web: INFO